---
title: "Blog Post 2"
subtitle: ""
author: ""
date: "2025-03-17"
image-alt: ""
categories: []
date-modified: "2025-03-17"
draft: false
---

## Data Source and Research Motivation

The data comes from the IPUMS website, an individual-level population database containing information for U.S. Census Data for Social, Economic, and Health Research. This dataset can be used to examine the racial disparities in land ownership. The importance of distinguishing between urban and rural residential properties provides insight for analyzing ownership patterns, housing distribution, and land usage across different demographic groups.

Historically, the American segregational economic policy has confined minority groups into urban areas, limiting their ability to acquire larger sets of land. Since land and homeownership are major contributors to generational wealth, the dataset can also explore how land distribution contributes to the racial wealth gap.

## Data Collection and Preprocessing Challenges

The process of finding this data was not very smooth. The data we downloaded through the website was very large, because it contained many valid variables. When processing the data, even though unnecessary data had been removed, the data size was still 78.9MB, which was larger than 50MB, so the dataset could only be reduced.

The current sample population is 3,405,811 rows. The table has up to a million rows, and sample bias does exist. For example, in the variable values, many entries are coded as `99999999`, which is obviously due to some kind of statistical limitation. The highest is only `99999999`, so if you really follow this data for statistics, the real value would be underestimated.

## IPUMS USA in Research and Policy

The IPUMS USA dataset is widely used in research and policymaking, providing microdata from U.S. censuses and the American Community Survey. Researchers have used it to study migration, labor markets, education, and housing trends, leveraging its longitudinal depth to track societal changes over time.

Policymakers rely on IPUMS data to guide urban planning, zoning laws, economic policies, and social programs. For example, housing lot size trends inform infrastructure and land-use decisions. Past research has explored questions like how immigration patterns impact the economy, what drives educational disparities, and how employment trends respond to economic cycles. By offering rich demographic insights, the dataset continues to shape both academic studies and policy development.
